
server:
  port:9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planninggood?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 200208066017Lu
    driver-class-name: com.mysql.cj.jdbc.Driver